<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType> 
        <!-- WinExe does NOT mean Windows Exe, it's just the legacy name for a standard app without a console. -->
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="FluentAvaloniaUI" Version="2.1.0" />
        <PackageReference Include="Avalonia" Version="11.1.2" />
        <PackageReference Include="Avalonia.Desktop" Version="11.1.2" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.1.2" Condition="'$(Configuration)' == 'Debug'" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.2" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.2" />
        <PackageReference Include="Projektanker.Icons.Avalonia.FontAwesome" Version="9.4.0"/>
        <PackageReference Include="MenuFactory" Version="1.1.0" />
        <PackageReference Include="ConfigFactory.Avalonia" Version="0.4.2" />
        <PackageReference Include="OneOf" Version="3.0.271" />
        
        <ProjectReference Include="../Bot/Volte.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <AvaloniaResource Include="../Bot/Resources/Volte.ico" Link="Assets\icon.ico" />
        <AvaloniaResource Include="Assets/**" />
    </ItemGroup>
    <ItemGroup>
      <Compile Update="Avalonia\VolteApp.axaml.cs">
        <DependentUpon>App.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Avalonia\Pages\Logs\LogsView.axaml.cs">
        <DependentUpon>LogsView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Avalonia\Pages\UIShellView.axaml.cs">
        <DependentUpon>UIShellView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
